### ISSUE TITLE
Shared Repository Helpdesk Proposal & Feedback

### ISSUE THREAD

**Issue by bettymakes** [ossf/wg-securing-software-repos#9]
As noted during the November 2, 2022 meeting, this issue has been created as a mechanism for us to collect questions and feedback about the [Shared Repository Helpdesk Proposal](https://docs.google.com/document/d/1Od9kqd4JIAW1h0vvvkD8NFclxsR8yudOdsZEMT7lBUc/edit#heading=h.mztvqya5xxdj).

**Comment by steiza** [comment]
This proposal is a great idea, but I think this effort has stalled out for the time being. I'm going to mark this as not planned, but we can bring it back if / when someone has interest in leading this proposal.
